project:
  type: website
  output-dir: ../docs

website:
  title: "CS25-307 Home"
  navbar:
    left:
      - href: project-plan.qmd
        text: Project Plan
      - href: status.qmd
        text: Weekly status
      - href: references.qmd
        text: References
      - href: working.qmd
        text: Working Docs
      - href: deliverables.qmd
        text: Deliverables
      - href: about.qmd
        text: About this site

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    